### ISSUE TITLE
How to configure Global Error Handler @RabbitListener annotation's errorHandler attribute 

### ISSUE THREAD

**Issue by deeps2633** [spring-projects/spring-amqp-samples#58]
Hi, I looked at your example of spring-rabbit-global-errorhandler. we already have a custom errorHandler which implements RabbitListenerErrorHandler interface which is configured by @RabbitListener annotation's attribute errorHandler. But this does'nt catch any ​MessageConversionExceptions.  I understand that those are caught by ConditionalRejectingErrorHandler.  we want to catch those type of problems and write to database. What's the best way to configure errorHandler to achieve this? 

Apologies if this is not the right place to ask this question.

**Comment by garyrussell** [comment]
You should ask questions on Stack Overflow, tagged with [spring-amqp].

That's exactly what that sample is for

https://github.com/spring-projects/spring-amqp-samples/blob/305bb698787745a50321be7e2b1ed723ae559ac5/spring-rabbit-global-errorhandler/src/main/java/org/springframework/amqp/samples/errorhandler/Application.java#L57

...it's error handle simply logs the exception and calls `super.isFatal()`.

https://github.com/spring-projects/spring-amqp-samples/blob/305bb698787745a50321be7e2b1ed723ae559ac5/spring-rabbit-global-errorhandler/src/main/java/org/springframework/amqp/samples/errorhandler/Application.java#L76-L91

**Comment by deeps2633** [comment]
Thank you for the response. In future I will ask in stack overflow. One last question, so I should maintain 2 error handlers then? one is our custom errorhandler implementing RabbitListenerErrorHandler  which handles retries of business exceptions and another at factory.setErrorHandler(errorHandler());  this level which handles message conversion exceptions?

**Comment by garyrussell** [comment]
Correct; the error handlers perform different functions. The `RabbitListenerErrorHandler` can only handle exceptions thrown by the `@RabbitListener` method.

It's different to the lower-level container error handler because it can be used, for example, to return an error message to the caller (if the listener method has a return type and is used for request/reply messaging). It also has access to the converted message payload.

The container error handler only has access to the raw unconverted `Message`; the listener error handler gets both the raw `Message` and converted `Message<?>`.

If you are not using request/reply messaging, or don't need to send information about a failure to the message sender, and you don't need access to the converted payload, you can just use the container error handler to function for all exception types.

**Comment by deeps2633** [comment]
Thank you so much, this helps a lot!!
